# Generated by Django 3.1.3 on 2020-11-30 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Memo',
        ),
    ]
