# Generated by Django 3.1.3 on 2020-12-03 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_blogdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdata',
            name='link',
        ),
    ]
