# Generated by Django 3.1.3 on 2020-12-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_remove_blogdata_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayTexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ko_text', models.CharField(max_length=200)),
                ('en_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='BlogData',
        ),
    ]
