# Generated by Django 3.1.3 on 2020-12-10 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_auto_20201209_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='post',
            new_name='memo',
        ),
    ]
